### ISSUE TITLE
 localization

### ISSUE THREAD

**Issue by FilippovAlexei** [devlinx9/muon-ssh#29]
Hi,  how to translate into another language.

**Comment by devlinx9** [comment]
If you want to translate into another language you have to download this file https://github.com/devlinx9/muon-ssh/blob/master/muon-app/src/main/java/muon/app/common/i18n/Messages_en.java and make the changes for your language and send it to me if you don't know how to code, otherwise, you have to add a new file for your language, base in other java file in the path master/muon-app/src/main/java/muon/app/common/i18n/ and make the changes then you have to add your new language in muon-app/src/main/java/util/Language.java and finally make a pull request.

Be attentive that you have to modify the second string in the Object resources in the Message_en.java class:
 {"general", "Em geral" *This string}
